version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
    reviewers:
      - "mongodb/apix-integrations"
