// Generated by cdk-import
import * as cdk from "aws-cdk-lib";
import * as constructs from "constructs";

/**
 * Creates and manages a Project Service Account. This resource creates a Service Account and assigns it to a project. Note: Deleting this resource only unassigns the Service Account from the project, but doesn't delete it from the organization.
 *
 * @schema CfnProjectServiceAccountProps
 */
export interface CfnProjectServiceAccountProps {
  /**
   * Profile used to provide credentials information.
   *
   * @schema CfnProjectServiceAccountProps#Profile
   */
  readonly profile?: string;

  /**
   * Unique 24-hexadecimal digit string that identifies your project.
   *
   * @schema CfnProjectServiceAccountProps#ProjectId
   */
  readonly projectId: string;

  /**
   * Human-readable name for the Service Account.
   *
   * @schema CfnProjectServiceAccountProps#Name
   */
  readonly name: string;

  /**
   * Human readable description for the Service Account.
   *
   * @schema CfnProjectServiceAccountProps#Description
   */
  readonly description: string;

  /**
   * A list of project-level roles for the Service Account.
   *
   * @schema CfnProjectServiceAccountProps#Roles
   */
  readonly roles: string[];

  /**
   * Expiration time of the new Service Account secret in hours.
   *
   * @schema CfnProjectServiceAccountProps#SecretExpiresAfterHours
   */
  readonly secretExpiresAfterHours: number;

  /**
   * List of secrets associated with the Service Account.
   *
   * @schema CfnProjectServiceAccountProps#Secrets
   */
  readonly secrets?: SecretDefinition[];
}

/**
 * Converts an object of type 'CfnProjectServiceAccountProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_CfnProjectServiceAccountProps(
  obj: CfnProjectServiceAccountProps | undefined
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    Profile: obj.profile,
    ProjectId: obj.projectId,
    Name: obj.name,
    Description: obj.description,
    Roles: obj.roles?.map((y) => y),
    SecretExpiresAfterHours: obj.secretExpiresAfterHours,
    Secrets: obj.secrets?.map((y) => toJson_SecretDefinition(y)),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }),
    {}
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema SecretDefinition
 */
export interface SecretDefinition {
  /**
   * Unique identifier of the secret.
   *
   * @schema SecretDefinition#Id
   */
  readonly id?: string;

  /**
   * Date and time that the secret was created on.
   *
   * @schema SecretDefinition#CreatedAt
   */
  readonly createdAt?: string;

  /**
   * Date and time when the secret expires.
   *
   * @schema SecretDefinition#ExpiresAt
   */
  readonly expiresAt?: string;

  /**
   * Date and time when the secret was last used.
   *
   * @schema SecretDefinition#LastUsedAt
   */
  readonly lastUsedAt?: string;

  /**
   * Masked value of the secret.
   *
   * @schema SecretDefinition#MaskedSecretValue
   */
  readonly maskedSecretValue?: string;

  /**
   * The secret value. Only returned on create.
   *
   * @schema SecretDefinition#Secret
   */
  readonly secret?: string;
}

/**
 * Converts an object of type 'SecretDefinition' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_SecretDefinition(
  obj: SecretDefinition | undefined
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    Id: obj.id,
    CreatedAt: obj.createdAt,
    ExpiresAt: obj.expiresAt,
    LastUsedAt: obj.lastUsedAt,
    MaskedSecretValue: obj.maskedSecretValue,
    Secret: obj.secret,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }),
    {}
  );
}
/* eslint-enable max-len, quote-props */

/**
 * A CloudFormation `MongoDB::Atlas::ProjectServiceAccount`
 *
 * @cloudformationResource MongoDB::Atlas::ProjectServiceAccount
 * @stability external
 */
export class CfnProjectServiceAccount extends cdk.CfnResource {
  /**
   * The CloudFormation resource type name for this resource class.
   */
  public static readonly CFN_RESOURCE_TYPE_NAME =
    "MongoDB::Atlas::ProjectServiceAccount";

  /**
   * Resource props.
   */
  public readonly props: CfnProjectServiceAccountProps;

  /**
   * Attribute `MongoDB::Atlas::ProjectServiceAccount.ClientId`
   */
  public readonly attrClientId: string;
  /**
   * Attribute `MongoDB::Atlas::ProjectServiceAccount.CreatedAt`
   */
  public readonly attrCreatedAt: string;

  /**
   * Create a new `MongoDB::Atlas::ProjectServiceAccount`.
   *
   * @param scope - scope in which this resource is defined
   * @param id    - scoped id of the resource
   * @param props - resource properties
   */
  constructor(
    scope: constructs.Construct,
    id: string,
    props: CfnProjectServiceAccountProps
  ) {
    super(scope, id, {
      type: CfnProjectServiceAccount.CFN_RESOURCE_TYPE_NAME,
      properties: toJson_CfnProjectServiceAccountProps(props)!,
    });

    this.props = props;

    this.attrClientId = cdk.Token.asString(this.getAtt("ClientId"));
    this.attrCreatedAt = cdk.Token.asString(this.getAtt("CreatedAt"));
  }
}
