// Generated by cdk-import
import * as cdk from "aws-cdk-lib";
import * as constructs from "constructs";

/**
 * The Private Endpoint creation flow consists of the creation of three related resources in the next order: 1. Atlas Private Endpoint Service 2. Aws VPC private Endpoint 3. Atlas Private Endpoint
 *
 * @schema CfnPrivateEndpointServiceProps
 */
export interface CfnPrivateEndpointServiceProps {
  /**
   * The profile is defined in AWS Secret manager. See [Secret Manager Profile setup (../../../examples/profile-secret.yaml)
   *
   * @schema CfnPrivateEndpointServiceProps#Profile
   */
  readonly profile?: string;

  /**
   * Error message pertaining to the AWS PrivateLink connection. Returns null if there are no errors.
   *
   * @schema CfnPrivateEndpointServiceProps#ErrorMessage
   */
  readonly errorMessage?: string;

  /**
   * Status of the Atlas PrivateEndpoint service connection
   *
   * @schema CfnPrivateEndpointServiceProps#Status
   */
  readonly status?: string;

  /**
   * Unique 24-hexadecimal digit string that identifies your project.
   *
   * @schema CfnPrivateEndpointServiceProps#ProjectId
   */
  readonly projectId: string;

  /**
   * Aws Region
   *
   * @schema CfnPrivateEndpointServiceProps#Region
   */
  readonly region: string;
}

/**
 * Converts an object of type 'CfnPrivateEndpointServiceProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_CfnPrivateEndpointServiceProps(
  obj: CfnPrivateEndpointServiceProps | undefined
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    Profile: obj.profile,
    ErrorMessage: obj.errorMessage,
    Status: obj.status,
    ProjectId: obj.projectId,
    Region: obj.region,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }),
    {}
  );
}
/* eslint-enable max-len, quote-props */

/**
 * A CloudFormation `MongoDB::Atlas::PrivateEndpointService`
 *
 * @cloudformationResource MongoDB::Atlas::PrivateEndpointService
 * @stability external
 */
export class CfnPrivateEndpointService extends cdk.CfnResource {
  /**
   * The CloudFormation resource type name for this resource class.
   */
  public static readonly CFN_RESOURCE_TYPE_NAME =
    "MongoDB::Atlas::PrivateEndpointService";

  /**
   * Resource props.
   */
  public readonly props: CfnPrivateEndpointServiceProps;

  /**
   * Attribute `MongoDB::Atlas::PrivateEndpointService.Id`
   */
  public readonly attrId: string;
  /**
   * Attribute `MongoDB::Atlas::PrivateEndpointService.InterfaceEndpoints`
   */
  public readonly attrInterfaceEndpoints: string[];
  /**
   * Attribute `MongoDB::Atlas::PrivateEndpointService.EndpointServiceName`
   */
  public readonly attrEndpointServiceName: string;

  /**
   * Create a new `MongoDB::Atlas::PrivateEndpointService`.
   *
   * @param scope - scope in which this resource is defined
   * @param id    - scoped id of the resource
   * @param props - resource properties
   */
  constructor(
    scope: constructs.Construct,
    id: string,
    props: CfnPrivateEndpointServiceProps
  ) {
    super(scope, id, {
      type: CfnPrivateEndpointService.CFN_RESOURCE_TYPE_NAME,
      properties: toJson_CfnPrivateEndpointServiceProps(props)!,
    });

    this.props = props;

    this.attrId = cdk.Token.asString(this.getAtt("Id"));
    this.attrInterfaceEndpoints = cdk.Token.asList(
      this.getAtt("InterfaceEndpoints")
    );
    this.attrEndpointServiceName = cdk.Token.asString(
      this.getAtt("EndpointServiceName")
    );
  }
}
