// Generated by cdk-import
import * as cdk from 'aws-cdk-lib';
import * as constructs from 'constructs';

/**
 * Manages IP access list entries for MongoDB Atlas Service Accounts at the organization level.
 *
 * @schema CfnServiceAccountAccessListEntryProps
 */
export interface CfnServiceAccountAccessListEntryProps {
  /**
   * Unique 24-hexadecimal digit string that identifies the organization.
   *
   * @schema CfnServiceAccountAccessListEntryProps#OrgId
   */
  readonly orgId: string;

  /**
   * The Client ID of the Service Account.
   *
   * @schema CfnServiceAccountAccessListEntryProps#ClientId
   */
  readonly clientId: string;

  /**
   * Range of IP addresses in CIDR notation to be added to the access list. You can set a value for this parameter or IPAddress, but not both.
   *
   * @schema CfnServiceAccountAccessListEntryProps#CIDRBlock
   */
  readonly cidrBlock?: string;

  /**
   * Single IP address to be added to the access list. You can set a value for this parameter or CIDRBlock, but not both.
   *
   * @schema CfnServiceAccountAccessListEntryProps#IPAddress
   */
  readonly ipAddress?: string;

  /**
   * Profile used to provide credentials information, (a secret with the cfn/atlas/profile/{Profile}, is required), if not provided default is used.
   *
   * @schema CfnServiceAccountAccessListEntryProps#Profile
   */
  readonly profile?: string;
}

/**
 * Converts an object of type 'CfnServiceAccountAccessListEntryProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_CfnServiceAccountAccessListEntryProps(obj: CfnServiceAccountAccessListEntryProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'OrgId': obj.orgId,
    'ClientId': obj.clientId,
    'CIDRBlock': obj.cidrBlock,
    'IPAddress': obj.ipAddress,
    'Profile': obj.profile,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */


/**
 * A CloudFormation `MongoDB::Atlas::ServiceAccountAccessListEntry`
 *
 * @cloudformationResource MongoDB::Atlas::ServiceAccountAccessListEntry
 * @stability external
 */
export class CfnServiceAccountAccessListEntry extends cdk.CfnResource {
  /**
  * The CloudFormation resource type name for this resource class.
  */
  public static readonly CFN_RESOURCE_TYPE_NAME = "MongoDB::Atlas::ServiceAccountAccessListEntry";

  /**
   * Resource props.
   */
  public readonly props: CfnServiceAccountAccessListEntryProps;

  /**
   * Attribute `MongoDB::Atlas::ServiceAccountAccessListEntry.CreatedAt`
   */
  public readonly attrCreatedAt: string;
  /**
   * Attribute `MongoDB::Atlas::ServiceAccountAccessListEntry.LastUsedAddress`
   */
  public readonly attrLastUsedAddress: string;
  /**
   * Attribute `MongoDB::Atlas::ServiceAccountAccessListEntry.LastUsedAt`
   */
  public readonly attrLastUsedAt: string;
  /**
   * Attribute `MongoDB::Atlas::ServiceAccountAccessListEntry.RequestCount`
   */
  public readonly attrRequestCount: number;

  /**
   * Create a new `MongoDB::Atlas::ServiceAccountAccessListEntry`.
   *
   * @param scope - scope in which this resource is defined
   * @param id    - scoped id of the resource
   * @param props - resource properties
   */
  constructor(scope: constructs.Construct, id: string, props: CfnServiceAccountAccessListEntryProps) {
    super(scope, id, { type: CfnServiceAccountAccessListEntry.CFN_RESOURCE_TYPE_NAME, properties: toJson_CfnServiceAccountAccessListEntryProps(props)! });

    this.props = props;

    this.attrCreatedAt = cdk.Token.asString(this.getAtt('CreatedAt'));
    this.attrLastUsedAddress = cdk.Token.asString(this.getAtt('LastUsedAddress'));
    this.attrLastUsedAt = cdk.Token.asString(this.getAtt('LastUsedAt'));
    this.attrRequestCount = cdk.Token.asNumber(this.getAtt('RequestCount'));
  }
}