// Generated by cdk-import
import * as cdk from "aws-cdk-lib";
import * as constructs from "constructs";

/**
 * Creates a secret for the specified Service Account at the project level.
 *
 * @schema CfnProjectServiceAccountSecretProps
 */
export interface CfnProjectServiceAccountSecretProps {
  /**
   * Unique 24-hexadecimal digit string that identifies your project.
   *
   * @schema CfnProjectServiceAccountSecretProps#ProjectId
   */
  readonly projectId: string;

  /**
   * The Client ID of the Service Account.
   *
   * @schema CfnProjectServiceAccountSecretProps#ClientId
   */
  readonly clientId: string;

  /**
   * The expiration time of the new Service Account secret, provided in hours. The minimum and maximum allowed expiration times are subject to change and are controlled by the organization's settings.
   *
   * @schema CfnProjectServiceAccountSecretProps#SecretExpiresAfterHours
   */
  readonly secretExpiresAfterHours?: number;

  /**
   * Profile used to provide credentials information, (a secret with the cfn/atlas/profile/{Profile}, is required), if not provided default is used.
   *
   * @schema CfnProjectServiceAccountSecretProps#Profile
   */
  readonly profile?: string;
}

/**
 * Converts an object of type 'CfnProjectServiceAccountSecretProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_CfnProjectServiceAccountSecretProps(
  obj: CfnProjectServiceAccountSecretProps | undefined
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    ProjectId: obj.projectId,
    ClientId: obj.clientId,
    SecretExpiresAfterHours: obj.secretExpiresAfterHours,
    Profile: obj.profile,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }),
    {}
  );
}
/* eslint-enable max-len, quote-props */

/**
 * A CloudFormation `MongoDB::Atlas::ProjectServiceAccountSecret`
 *
 * @cloudformationResource MongoDB::Atlas::ProjectServiceAccountSecret
 * @stability external
 */
export class CfnProjectServiceAccountSecret extends cdk.CfnResource {
  /**
   * The CloudFormation resource type name for this resource class.
   */
  public static readonly CFN_RESOURCE_TYPE_NAME =
    "MongoDB::Atlas::ProjectServiceAccountSecret";

  /**
   * Resource props.
   */
  public readonly props: CfnProjectServiceAccountSecretProps;

  /**
   * Attribute `MongoDB::Atlas::ProjectServiceAccountSecret.SecretId`
   */
  public readonly attrSecretId: string;
  /**
   * Attribute `MongoDB::Atlas::ProjectServiceAccountSecret.Secret`
   */
  public readonly attrSecret: string;
  /**
   * Attribute `MongoDB::Atlas::ProjectServiceAccountSecret.MaskedSecretValue`
   */
  public readonly attrMaskedSecretValue: string;
  /**
   * Attribute `MongoDB::Atlas::ProjectServiceAccountSecret.CreatedAt`
   */
  public readonly attrCreatedAt: string;
  /**
   * Attribute `MongoDB::Atlas::ProjectServiceAccountSecret.ExpiresAt`
   */
  public readonly attrExpiresAt: string;
  /**
   * Attribute `MongoDB::Atlas::ProjectServiceAccountSecret.LastUsedAt`
   */
  public readonly attrLastUsedAt: string;

  /**
   * Create a new `MongoDB::Atlas::ProjectServiceAccountSecret`.
   *
   * @param scope - scope in which this resource is defined
   * @param id    - scoped id of the resource
   * @param props - resource properties
   */
  constructor(
    scope: constructs.Construct,
    id: string,
    props: CfnProjectServiceAccountSecretProps
  ) {
    super(scope, id, {
      type: CfnProjectServiceAccountSecret.CFN_RESOURCE_TYPE_NAME,
      properties: toJson_CfnProjectServiceAccountSecretProps(props)!,
    });

    this.props = props;

    this.attrSecretId = cdk.Token.asString(this.getAtt("SecretId"));
    this.attrSecret = cdk.Token.asString(this.getAtt("Secret"));
    this.attrMaskedSecretValue = cdk.Token.asString(
      this.getAtt("MaskedSecretValue")
    );
    this.attrCreatedAt = cdk.Token.asString(this.getAtt("CreatedAt"));
    this.attrExpiresAt = cdk.Token.asString(this.getAtt("ExpiresAt"));
    this.attrLastUsedAt = cdk.Token.asString(this.getAtt("LastUsedAt"));
  }
}
