// Generated by cdk-import
import * as cdk from "aws-cdk-lib";
import * as constructs from "constructs";

/**
 * Creates and manages a Service Account for an organization.
 *
 * @schema CfnServiceAccountProps
 */
export interface CfnServiceAccountProps {
  /**
   * Profile used to provide credentials information.
   *
   * @schema CfnServiceAccountProps#Profile
   */
  readonly profile?: string;

  /**
   * Unique 24-hexadecimal digit string that identifies the organization.
   *
   * @schema CfnServiceAccountProps#OrgId
   */
  readonly orgId: string;

  /**
   * Human-readable name for the Service Account.
   *
   * @schema CfnServiceAccountProps#Name
   */
  readonly name: string;

  /**
   * Human readable description for the Service Account.
   *
   * @schema CfnServiceAccountProps#Description
   */
  readonly description: string;

  /**
   * List of organization-level roles for the Service Account.
   *
   * @schema CfnServiceAccountProps#Roles
   */
  readonly roles: string[];

  /**
   * Expiration time of the new Service Account secret in hours.
   *
   * @schema CfnServiceAccountProps#SecretExpiresAfterHours
   */
  readonly secretExpiresAfterHours: number;

  /**
   * List of secrets associated with the Service Account.
   *
   * @schema CfnServiceAccountProps#Secrets
   */
  readonly secrets?: Secret[];
}

/**
 * Converts an object of type 'CfnServiceAccountProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_CfnServiceAccountProps(
  obj: CfnServiceAccountProps | undefined
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    Profile: obj.profile,
    OrgId: obj.orgId,
    Name: obj.name,
    Description: obj.description,
    Roles: obj.roles?.map((y) => y),
    SecretExpiresAfterHours: obj.secretExpiresAfterHours,
    Secrets: obj.secrets?.map((y) => toJson_Secret(y)),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }),
    {}
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema Secret
 */
export interface Secret {
  /**
   * Unique identifier of the secret.
   *
   * @schema Secret#Id
   */
  readonly id?: string;

  /**
   * Date and time that the secret was created on.
   *
   * @schema Secret#CreatedAt
   */
  readonly createdAt?: string;

  /**
   * Date and time when the secret expires.
   *
   * @schema Secret#ExpiresAt
   */
  readonly expiresAt?: string;

  /**
   * Date and time when the secret was last used.
   *
   * @schema Secret#LastUsedAt
   */
  readonly lastUsedAt?: string;

  /**
   * Masked value of the secret.
   *
   * @schema Secret#MaskedSecretValue
   */
  readonly maskedSecretValue?: string;

  /**
   * The secret value. Only returned on create.
   *
   * @schema Secret#Secret
   */
  readonly secret?: string;
}

/**
 * Converts an object of type 'Secret' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_Secret(
  obj: Secret | undefined
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    Id: obj.id,
    CreatedAt: obj.createdAt,
    ExpiresAt: obj.expiresAt,
    LastUsedAt: obj.lastUsedAt,
    MaskedSecretValue: obj.maskedSecretValue,
    Secret: obj.secret,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }),
    {}
  );
}
/* eslint-enable max-len, quote-props */

/**
 * A CloudFormation `MongoDB::Atlas::ServiceAccount`
 *
 * @cloudformationResource MongoDB::Atlas::ServiceAccount
 * @stability external
 */
export class CfnServiceAccount extends cdk.CfnResource {
  /**
   * The CloudFormation resource type name for this resource class.
   */
  public static readonly CFN_RESOURCE_TYPE_NAME =
    "MongoDB::Atlas::ServiceAccount";

  /**
   * Resource props.
   */
  public readonly props: CfnServiceAccountProps;

  /**
   * Attribute `MongoDB::Atlas::ServiceAccount.ClientId`
   */
  public readonly attrClientId: string;
  /**
   * Attribute `MongoDB::Atlas::ServiceAccount.CreatedAt`
   */
  public readonly attrCreatedAt: string;

  /**
   * Create a new `MongoDB::Atlas::ServiceAccount`.
   *
   * @param scope - scope in which this resource is defined
   * @param id    - scoped id of the resource
   * @param props - resource properties
   */
  constructor(
    scope: constructs.Construct,
    id: string,
    props: CfnServiceAccountProps
  ) {
    super(scope, id, {
      type: CfnServiceAccount.CFN_RESOURCE_TYPE_NAME,
      properties: toJson_CfnServiceAccountProps(props)!,
    });

    this.props = props;

    this.attrClientId = cdk.Token.asString(this.getAtt("ClientId"));
    this.attrCreatedAt = cdk.Token.asString(this.getAtt("CreatedAt"));
  }
}
