// Generated by cdk-import
import * as cdk from 'aws-cdk-lib';
import * as constructs from 'constructs';

/**
 * Assigns a Service Account to a Project with specified roles in MongoDB Atlas.
 *
 * @schema CfnServiceAccountProjectAssignmentProps
 */
export interface CfnServiceAccountProjectAssignmentProps {
  /**
   * Unique 24-hexadecimal digit string that identifies the organization. Required for List operation.
   *
   * @schema CfnServiceAccountProjectAssignmentProps#OrgId
   */
  readonly orgId?: string;

  /**
   * The Client ID of the Service Account.
   *
   * @schema CfnServiceAccountProjectAssignmentProps#ClientId
   */
  readonly clientId: string;

  /**
   * Unique 24-hexadecimal digit string that identifies your project.
   *
   * @schema CfnServiceAccountProjectAssignmentProps#ProjectId
   */
  readonly projectId: string;

  /**
   * The Project permissions for the Service Account in the specified Project.
   *
   * @schema CfnServiceAccountProjectAssignmentProps#Roles
   */
  readonly roles: string[];

  /**
   * Profile used to provide credentials information, (a secret with the cfn/atlas/profile/{Profile}, is required), if not provided default is used
   *
   * @schema CfnServiceAccountProjectAssignmentProps#Profile
   */
  readonly profile?: string;
}

/**
 * Converts an object of type 'CfnServiceAccountProjectAssignmentProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_CfnServiceAccountProjectAssignmentProps(obj: CfnServiceAccountProjectAssignmentProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'OrgId': obj.orgId,
    'ClientId': obj.clientId,
    'ProjectId': obj.projectId,
    'Roles': obj.roles?.map(y => y),
    'Profile': obj.profile,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */


/**
 * A CloudFormation `MongoDB::Atlas::ServiceAccountProjectAssignment`
 *
 * @cloudformationResource MongoDB::Atlas::ServiceAccountProjectAssignment
 * @stability external
 */
export class CfnServiceAccountProjectAssignment extends cdk.CfnResource {
  /**
  * The CloudFormation resource type name for this resource class.
  */
  public static readonly CFN_RESOURCE_TYPE_NAME = "MongoDB::Atlas::ServiceAccountProjectAssignment";

  /**
   * Resource props.
   */
  public readonly props: CfnServiceAccountProjectAssignmentProps;


  /**
   * Create a new `MongoDB::Atlas::ServiceAccountProjectAssignment`.
   *
   * @param scope - scope in which this resource is defined
   * @param id    - scoped id of the resource
   * @param props - resource properties
   */
  constructor(scope: constructs.Construct, id: string, props: CfnServiceAccountProjectAssignmentProps) {
    super(scope, id, { type: CfnServiceAccountProjectAssignment.CFN_RESOURCE_TYPE_NAME, properties: toJson_CfnServiceAccountProjectAssignmentProps(props)! });

    this.props = props;

  }
}