---
name: Package CDK
on:
  workflow_call: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: 24.x
      - name: Install dependencies
        run: npm ci
      - name: build
        run: npx projen build
  package-js:
    needs: build
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: 24.x
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Install Dependencies
        run: npm ci
      - name: Create js artifact
        run: npx projen compile && npx projen package:js
  package-java:
    needs: build
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961
        with:
          distribution: temurin
          java-version: 21.x
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: 24.x
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Install Dependencies
        run: npm ci
      - name: Create java artifact
        run: npx projen compile && npx projen package:java
  package-python:
    needs: build
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: 3.x
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: 24.x
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Install Dependencies
        run: npm ci
      - name: Create python artifact
        run: npx projen compile && npx projen package:python
  package-dotnet:
    needs: build
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68
        with:
          dotnet-version: 9.0.x
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: 24.x
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Install Dependencies
        run: npm ci
      - name: Create dotnet artifact
        run: npx projen compile && npx projen package:dotnet

  package-go:
    needs: build
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
        with:
          go-version: ^1.25.0
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: 24.x
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Install Dependencies
        run: npm ci
      - name: Create go artifact
        run: npx projen compile && npx projen package:go

